# Generated by Django 6.0.3 on 2026-04-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('career_objective', models.TextField()),
                ('education', models.TextField()),
                ('t_skills', models.TextField()),
                ('s_skills', models.TextField()),
                ('projects', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
